project:
  type: website
  output-dir: docs

website:
  title: "quarto5"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.amd
        text: About
      - href: lab.qmd
        text: Lab
      - href: project.qmd
        text: Project
      - href: presentation.qmd
        text: Presentation

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

